# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FireBaseIOS3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FireBaseIOS3
	pod 'FirebaseCore'
	pod 'FirebaseAuth'
	pod 'Firebase/Firestore'
	pod 'Firebase/Database'
end
