# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HoWing' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HoWing
	
	pod 'Kingfisher'
	pod 'Alamofire'
	pod 'SwiftyJSON'
	pod 'Cosmos'
	pod 'TinyConstraints'
	pod 'CardSlider'
	pod 'FirebaseCore'
	pod 'FirebaseAuth'
	pod 'Firebase/Firestore'

end
